### ISSUE TITLE
XBOX support

### ISSUE THREAD

**Issue by bsviglo** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#39] opened 2022-04-18 13:49 UTC
Is it possible to use this library to port game\engine DX12 renderer from Windows to consoles (XBOX ONE S/X, XBOX SERIES S/X) ? Or we need to do some adjustments?

**Comment by adam-sawicki-a** [comment] 2022-04-19 09:01
Yes, it might be possible to use the library on Xbox as the platform also offers Direct3D API. I have some anecdotal information about it being used on Windows + Xbox in some projects. But for now Xbox is not officially supported by the library, only PC Windows. Some adjustments to the code may be required.

Closing this ticket as a duplicate of #16

**Closed by adam-sawicki-a** 2022-04-19 09:01 UTC
